config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show, :edit, :update]

  resources :projects do
    resources :tasks, only: [:new, :edit, :create, :update, :destroy]
    resources :permissions
    resources :sections, only: [:index, :create, :update, :destroy] do
      resources :tasks, only: [:new, :edit, :destroy]
    end
  end

  resources :assignments

  resources :tasks, only: [:index, :create, :update]
  get '/mytasks', to: 'tasks#index'

  resources :sessions, only: [:create]
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  get '/auth/facebook/callback', to: 'sessions#create'

  get '/home', to: 'users#show', as: 'home'
  get '/about', to: 'static#about'
  root 'static#index'

end

app/models/task.rb
class Task < ApplicationRecord
  validates :content, presence: true
  validate :date_cannot_earlier_than_today, on: :create

  belongs_to :project
  has_one :assignment, dependent: :destroy
  accepts_nested_attributes_for :assignment, reject_if: :no_assignee

  #self join
  has_many :subtasks, class_name: "Task", foreign_key: "parent_id"
  belongs_to :parent, class_name: "Task", optional: true

  #validation method
  def date_cannot_earlier_than_today
    if deadline && deadline < Time.zone.today
      errors.add(:deadline, "can't be set in the past")
    end
  end

  def no_assignee(attributes)
    attributes['user_id'].blank?
  end

  def human_time
    self.deadline.strftime("%a, %B %-d, %Y")
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :confirm_owner, only: [:destroy]
  before_action :confirm_manager_or_owner, only: [:new, :create]
  
  def index
    #needs to work on its own and with a nested route
    if params[:project_id]
    else
      @tasks = Assignment.user_list(current_user)
    end
  end
  
  def new
    @task = Task.new do |t|
      if params[:section_id]
        @section = Section.find_by(id: params[:section_id])
        t.section_id = params[:section_id]
      end
      t.build_assignment
    end
    @project = Project.find_by(id: params[:project_id])
    @collaborators = @project.collaborators
  end

  def create
    @project = Project.find_by(id: params[:task][:project_id])
    @task = Task.new(task_params)
    if @task.save
      flash[:success] = "Task created."
      redirect_to project_path(@task.project)
    else
      #includes assignment options if no assignment was submitted
      @task.assignment = Assignment.new
      @collaborators = @project.collaborators
      flash.now[:errors] = @task.errors.full_messages
      render :new
    end
  end

  def edit
    set_task
    if @task.assignment.nil?
      @task.build_assignment
    end
    session[:return_to] = request.referer
    @project = @task.project
    @collaborators = @project.collaborators
  end

  def update
    set_task
    if @task.update(task_params)
      #addresses ability to remove an existing assignment via edit
      if @task.assignment && params[:task][:assignment_attributes].present? && params[:task][:assignment_attributes][:user_id].blank?
        @task.assignment.destroy
      end
      flash[:success] = "Task updated."
      #post-completion and post-edit redirects to origination location
      if params[:task][:project_id].present?
        redirect_to project_path(@task.project)
      elsif session[:return_to]
        redirect_to session.delete(:return_to)
      else
        redirect_to mytasks_path
      end
    else
      flash.now[:errors] = @task.errors.full_messages
      render :edit
    end
  end

  def destroy
    set_task
    @project = @task.project
    @task.destroy
    redirect_to project_path(@project)
  end

  private

  def set_task
    @task = Task.find_by_id(params[:id])
  end

  def task_params
    params.require(:task).permit(:content, :deadline, :project_id, :section_id, :parent_id, :status, assignment_attributes: [:user_id, :id])
  end
end

app/views/tasks/_complete_button.html.erb
<div class="task-component">
    <%= form_with(model: task, local: true) do |f| %>
        <%= f.hidden_field :status, value: "complete" %>
        <% if defined?(project) %>
            <%= f.hidden_field :project_id, value: project.id %>
        <% end %>
        <div class="complete icon flex-icon">
            <%= f.submit value: "" %>
        </div>
    <% end %>
</div>

app/views/tasks/_delete_button.html.erb
<div class="task-component">
    <%= form_with(model: task, method: :delete, url: [project, task]) do |f| %>
        <div class="delete icon flex-icon">
        <%= f.submit value: "" %>
        </div>
    <% end %>
</div>

app/views/tasks/_edit_button.html.erb
<div class="task-component">
    <%= link_to edit_project_task_path(project, task) do %>
        <div class="edit icon"></div>
    <% end %>
</div>

app/views/tasks/_form.html.erb
  
  <div class="field">
  <label>Task description</label><br>
  <%= f.text_field :content %>
  </div>

  <div class="field">
  <%= f.collection_select :section_id, sections, :id, :name, include_blank: "Select a Section" %>
  </div>

  <div class="field">
  <label for="deadline">Goal Date</label><br>
  <%= f.date_field :deadline %>
  </div>

  <%= f.fields_for :assignment do |a| %>
    <div class="field">
      <%= a.collection_select :user_id, collaborators, :id, :first_name, include_blank: "Assign to a Collaborator" %>
    </div>
  <% end %>



app/views/tasks/_preview_user_task_list.html.erb
<td>
  <div class="icon-container">
   <%= t.content %>
  </div>
</td>

<td>
  <%= link_to t.project.title, project_path(t.project) %> 
</td>

<td>
<% if t.deadline %>
  <%= t.human_time%>
<% end %>
</td>

app/views/tasks/_task_list.html.erb
<td>
  <div class="icon-container">
    <%# task complete button %>
    <% if t.status == "complete" %>
      <div class="completed icon"></div>
    <% else %>
        <%= render partial: '/tasks/complete_button', locals: { task: t, project: project } %>
    <% end %>
  </div>
</td>

<td>
  <div class="icon-container">
    <%= t.content %>
    <% unless project.managers_plus.exclude?(current_user) %>
      <%# task edit button %>
      <%= render partial: '/tasks/edit_button', locals: { task: t, project: project }%>
      <%# task delete button %>
      <%= render partial: '/tasks/delete_button', locals: { task: t, project: project } %>
    <% end %>
  </div>
</td>

<td>
<% if t.deadline %>
  <%= t.human_time%>
<% end %>
</td>

<td>
  <% if t.assignment %>
    <%= t.assignment.user.display_name %>
  <% elsif t.status == "open" && project.managers_plus.include?(current_user)%>
    <%= form_with model: assignment, url: '/assignments' do |f| %>
      <%= f.hidden_field :task_id, value: t.id %>
      <%= f.collection_select :user_id, collaborators, :id, :first_name %>
      <%= f.submit "Assign" %>
    <% end %>
  <% end %>
</td>

app/views/tasks/_user_task_list.html.erb
<td>
  <div class="icon-container">
    <%# task complete button %>
    <%= render partial: '/tasks/complete_button', locals: { task: t } %>
  </div>
</td>

<td>
  <div class="icon-container">
    <% unless t.project.managers_plus.exclude?(current_user) %>
      <%= t.content %>
      <%# task edit button %>
      <%= render partial: '/tasks/edit_button', locals: { task: t, project: t.project } %>
      <%# task delete button %>
      <%= render partial: '/tasks/delete_button', locals: { task: t, project: t.project }%>
    <% end %>
  </div>
</td>

<td>
  <%= link_to t.project.title, project_path(t.project) %> 
</td>

<td>
<% if t.deadline %>
  <%= t.human_time%>
<% end %>
</td>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= form_with(model: @task, local: true) do |f| %>

  <%= render partial: 'form', locals: {f: f, sections: @project.sections, collaborators: @collaborators} %>

  <%= f.submit "Update Task"%>

<% end %>

<p>Back to <%= link_to @project.title, project_path(@project) %></p>

app/views/tasks/index.html.erb
<h1>All Tasks</h1>

<%= render partial: '/layouts/flash_message_center' %>

<table>
<tr>
<th></th>
<th>Task</th>
<th>Project</th>
<th>Deadline</th>
</tr>

<% @tasks.each do |t| %>
  <tr>
    <%= render partial: '/tasks/user_task_list', locals: { t: t } %>
  </tr>
<% end %>

</table>


app/views/tasks/new.html.erb
<h1>Add a Task <% if @section %><%= "to #{@section.name}" %><% end %></h1>

<%= render partial: '/layouts/flash_message_center' %>

<%= form_with(model: @task, url: [@project, @task], local: true) do |f| %>

  <%= render partial: 'form', locals: {f: f, sections: @project.sections, collaborators: @collaborators} %>

  <%= f.hidden_field :project_id, value: @project.id %>

  <%= f.submit "Add Task"%>

<% end %>

<p>Back to <%= link_to @project.title, project_path(@project) %></p>