config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show, :edit, :update]

  resources :projects do
    resources :tasks, only: [:new, :edit, :create, :update, :destroy]
    resources :permissions
    resources :sections, only: [:index, :create, :update, :destroy] do
      resources :tasks, only: [:new, :edit, :destroy]
    end
  end

  resources :assignments

  resources :tasks, only: [:index, :create, :update]
  get '/mytasks', to: 'tasks#index'

  resources :sessions, only: [:create]
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  get '/auth/facebook/callback', to: 'sessions#create'

  get '/home', to: 'users#show', as: 'home'
  get '/about', to: 'static#about'
  root 'static#index'

end

app/models/project.rb
class Project < ApplicationRecord
  has_many :permissions, dependent: :destroy
  has_many :users, through: :permissions
  has_many :tasks, dependent: :destroy
  has_many :sections, dependent: :destroy

  validates :title, presence: true
  
  def set_owner(current_user)
    Permission.create(project_id: self.id, user_id: current_user.id, creator_id: current_user.id, access_level: "owner", accepted: true)
  end

  def owners
    owners = []
    self.permissions.where(access_level: "owner").each do |owner|
      owners << owner.user
    end
    owners
  end

  def managers_plus
    managers_plus = []
    self.permissions.where(access_level: "owner").or(self.permissions.where(access_level: "manager")).each do |plus|
      managers_plus << plus.user
    end
    managers_plus
  end

  def verify_owner(user)
    self.owners.include?(user)
  end

  def collaborators_with_access_level
    collaborators = []
    self.permissions.each do |c|
      collaborators << [c.user, c.access_level, c]
    end
    collaborators
  end

  def collaborators
    collaborators = []
    self.permissions.each do |c|
      collaborators << c.user
    end
    collaborators
  end

  def human_time
    if self.deadline
     self.deadline.strftime("%a, %B %-d, %Y")
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :confirm_owner, only: [:edit, :update, :destroy]

  def index
    @user_projects = current_user.user_projects
  end
  
  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      @project.set_owner(current_user)
      redirect_to project_path(@project)
    else
      flash.now[:errors] = @project.errors.full_messages
      render :new
    end
  end

  def show
    find_project
    @owners = @project.owners
    @collaborator_list = @project.collaborators_with_access_level
    @collaborators = @project.collaborators
    @sections = Section.where(project_id: @project.id)
    @loose_tasks = @project.tasks.where(section_id: nil)
    @assignment = Assignment.new
  end

  def edit
    find_project
  end

  def update
    find_project
    if @project.update(project_params)
      redirect_to project_path(@project)
    else
      flash.now[:errors] = @project.errors.full_messages
      render :edit
    end
  end

  def destroy
    find_project
  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :deadline)
  end

  def find_project
    @project = Project.find_by_id(params[:id])
  end

end

app/views/projects/_form.html.erb
<div class="field">
<label for="title">Title</label><br>
<%= f.text_field :title %>
</div>

<div class="field">
<label for="description">Description</label><br>
<%= f.text_field :description %>
</div>

<div class="field">
<label for="deadline">Goal Date</label><br>
<%= f.date_field :deadline, min: Time.zone.today %>
</div>

app/views/projects/_project_list.html.erb
<table>
<th>
Project
</th>
<th>
Description
</th>
<th>
Deadline
</th>
<th>
Role
</th>
<% user_projects.each do |project| %>
  <tr>
  <td>
  <strong><%= link_to project[0].title, project_path(project[0]) %></strong>
  </td>

  <td>
  <em><%= project[0].description %></em>
  </td>
  
  <td>
  <%= project[0].human_time %>
  </td>
  
  <td>
  <%= project[1].titlecase %>  
  </td>

  </tr>

<% end %>
</table>

app/views/projects/edit.html.erb
<h1>Edit Project Details</h1>

<%= form_with(model: @project, local: true) do |f| %>

  <%= render partial: 'form', locals: {f: f} %>

<%= f.submit %>
<% end %>

<p>Back to <%= link_to @project.title, project_path(@project) %></p>

app/views/projects/index.html.erb
<h1 class="title">Your Projects</h1>

<%= render partial: 'project_list', locals: {user_projects: @user_projects} %>

<p>
<%= link_to "Create a new project", new_project_path %>
</p>

app/views/projects/new.html.erb
<h1>Start a Project</h1>

<%= render partial: '/layouts/flash_message_center' %>

<%= form_with(model: @project, local: true) do |f| %>

  <%= render partial: 'form', locals: {f: f} %>

<%= f.submit %>
<% end %>

app/views/projects/show.html.erb
<h1 class="title"><%= @project.title %></h1>
<p class="description"><%= @project.description %></p>

<%= render partial: '/layouts/flash_message_center' %>

<p>Project Owners: 

<% @owners.each do |owner| %>
  <%= owner.full_name%><%= ", " unless owner == @owners.last%>
<% end %>
 — <%= link_to "View and add collaborators", project_permissions_path(@project) %>

<p>Due date: <%= @project.human_time %><% if @project.managers_plus.include?(current_user) %> — <%= link_to "Edit project details", edit_project_path(@project) %></p>

<h3><%= link_to "Create and edit sections", project_sections_path(@project) %></h3><% end %>

<h2>Tasks <% unless @project.managers_plus.exclude?(current_user) %><%= link_to new_project_task_path(@project) do %><div class="add inline-icon icon-small"></div><% end %><% end %></h2>

<% if @loose_tasks %>

<table>
    <tr>
    <th></th>
    <th>Task</th>
    <th>Deadline</th>
    <th>Assigned To</th>
    </tr>

  <% @loose_tasks.where.not(status: "complete").each do |t| %>
    <tr>
      <%= render partial: '/tasks/task_list', locals: {t: t, assignment: @assignment, collaborators: @collaborators, project: @project } %>
    </tr>
  <% end %>

  <% @loose_tasks.where(status: "complete").each do |t| %>
    <tr class="completed-content">
      <%= render partial: '/tasks/task_list', locals: {t: t, assignment: @assignment, collaborators: @collaborators, project: @project } %>
    </tr>
  <% end %>


  </table>
<% end %>

<% @sections.each do |section| %>
  <h3><%= section.name %> <% unless @project.managers_plus.exclude?(current_user) %><%= link_to new_project_section_task_path(@project, section) do %><div class="add icon-small inline-icon"></div><% end %><% end %></h3>

    <% if section.tasks %>

    <table>
      <tr>
      <th></th>
      <th>Task</th>
      <th>Deadline</th>
      <th>Assigned To</th>
      </tr>

    <% section.tasks.where.not(status: "complete").each do |t| %>
      <tr>
        <%= render partial: '/tasks/task_list', locals: {t: t, assignment: @assignment, collaborators: @collaborators, project: @project } %>
      </tr>
    <% end %>

    <% section.tasks.where(status: "complete").each do |t| %>
      <tr class="completed-content">
        <%= render partial: '/tasks/task_list', locals: {t: t, assignment: @assignment, collaborators: @collaborators, project: @project } %>
      </tr>
    <% end %>

    </table>
  <% end %>
<% end %>