config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show, :edit, :update]

  resources :projects do
    resources :tasks, only: [:new, :edit, :create, :update, :destroy]
    resources :permissions
    resources :sections, only: [:index, :create, :update, :destroy] do
      resources :tasks, only: [:new, :edit, :destroy]
    end
  end

  resources :assignments

  resources :tasks, only: [:index, :create, :update]
  get '/mytasks', to: 'tasks#index'

  resources :sessions, only: [:create]
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  get '/auth/facebook/callback', to: 'sessions#create'

  get '/home', to: 'users#show', as: 'home'
  get '/about', to: 'static#about'
  root 'static#index'

end

app/models/permission.rb
class Permission < ApplicationRecord
  belongs_to :user
  belongs_to :project
  belongs_to :creator, class_name: "User"

  validates :access_level, presence: true 
  
end

app/controllers/permissions_controller.rb
class PermissionsController < ApplicationController
  before_action :confirm_owner, except: [:index, :update]

  def index
    @project = Project.find_by(id: params[:project_id])
    @collaborator_list = @project.collaborators_with_access_level
    @permission = Permission.new
  end

  def create
    @user = User.find_by(email: params[:permission][:user_email])
    @project = Project.find_by(id: params[:project_id])
    if @user && @project.collaborators.exclude?(@user)
      @permission = Permission.new(permissions_params.except("user_email"))
      @permission.user_id = @user.id
      @permission.save
      redirect_to project_permissions_path(params[:project_id])
    elsif @user && @project.collaborators.include?(@user)
      @collaborator_list = @project.collaborators_with_access_level
      @permission = Permission.new
      flash.now[:error] = "#{@user.full_name} is already a collaborator on this project."
      render :index
    else
      @collaborator_list = @project.collaborators_with_access_level
      @permission = Permission.new
      flash.now[:error] = "The email address #{params[:permission][:user_email]} is not currently associated with a Tandem user."
      render :index
    end
  end

  def show
    @permission = Permission.find_by(id: params[:id])
    @project = Project.find_by(id: params[:project_id])
  end

  def edit
    @permission = Permission.find_by(id: params[:id])
    @project = Project.find_by(id: params[:project_id])
    @user = @permission.user
  end

  def update
    @permission = Permission.find_by(id: params[:id])
    @permission.update(permissions_params)
    redirect_to project_permissions_path(@permission.project)
  end

  def destroy
    @permission = Permission.find_by(id: params[:id])
    @permission.destroy
    redirect_to project_permissions_path(@permission.project)
  end

  private

  def permissions_params
    params.require(:permission).permit(:project_id, :user_email, :creator_id, :access_level, :accepted)
  end

end

app/views/permissions/edit.html.erb
<h1>Editing Permission for <%= @project.title %></h1>

<h3>Permission Overview: <%= @user.full_name %></h3>
<ul>
<li>Access Level: <%= @permission.access_level %></li>
<li>Email: <%= @user.email %></li>
<% if @permission.creator == @user %>
  <li>Created <%= @project.title %> on <%= @permission.created_at.strftime("%B %-d, %Y") %></li>
<% else %>
  <li>Added by <%= @permission.creator.full_name %> on <%= @permission.created_at.strftime("%B %-d, %Y") %></li>
<% end %>
</ul>

<h3>Update Access Level</h3>
<%= form_with(model: @permission, url: [@project, @permission], local: true) do |f| %>
<%= f.select :access_level, ["owner", "manager", "contributor"] %>
<%= f.submit "Update" %>
<% end %>

app/views/permissions/index.html.erb
<h1>Permissions: <%= @project.title %></h1>

<h3>Current Collaborators</h3>
<table>
<th>
Name
</th>
<th>
Email
</th>
<th>
Access Level
</th>
<% if @project.verify_owner(current_user) %>
  <th>
  Actions
  </th>
<% end %>

<% @collaborator_list.each do |collaborator|%>
  <tr <% if collaborator[2].accepted? == false %>class="pending"<% end %>>
    <td>
      <%= collaborator[0].full_name %>
    </td>
    <td>
      <%= collaborator[0].email %>
    </td>
    <td>
      <%= collaborator[1].titlecase %> <% if collaborator[2].accepted? == false %>(Invitation pending)<% end %> 
    </td>
    <% if @project.verify_owner(current_user) %>
    <td>
      <div class="icon-container">
        <%= link_to edit_project_permission_path(@project, collaborator[2]) do %><div class="edit icon flex-icon"></div><% end %>
        <%= link_to project_permission_path(@project, collaborator[2]) do %><div class="delete icon flex-icon"></div><% end %>
      </div>
    </td>
    <% end %>
  </tr>
<% end %>
</table>


<% if @project.verify_owner(current_user) %>

  <h3>Invite a New Collaborator</h3>
  <p>To add a new collaborator to your project:</p>
  <ol>
  <li>Make sure they have an account on Tandem</li>
  <li>Select a level of access to grant your new collaborator</li>
  <li>Enter their email below to send an invite</li>
  </ol> 

  <%= render partial: '/layouts/flash_message_center' %>

  <%= form_with(model: @permission, url: [@project, @permission], local: true) do |f| %>
  <div>
  <label>Select Access Level: </label>
  <%= f.select :access_level, ["owner", "manager", "contributor"] %>
  </div>

  <div>
  <label>Email: </label>
  <%= f.email_field :user_email %>
  </div>
  
  <%= f.hidden_field :project_id, value: @project.id %>
  <%= f.hidden_field :creator_id, value: current_user.id %>

  <%= f.submit "Invite Collaborator "%>
  <% end %>

<% end %>

<p>Back to <%= link_to @project.title, project_path(@project) %></p>