config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show, :edit, :update]

  resources :projects do
    resources :tasks, only: [:new, :edit, :create, :update, :destroy]
    resources :permissions
    resources :sections, only: [:index, :create, :update, :destroy] do
      resources :tasks, only: [:new, :edit, :destroy]
    end
  end

  resources :assignments

  resources :tasks, only: [:index, :create, :update]
  get '/mytasks', to: 'tasks#index'

  resources :sessions, only: [:create]
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  get '/auth/facebook/callback', to: 'sessions#create'

  get '/home', to: 'users#show', as: 'home'
  get '/about', to: 'static#about'
  root 'static#index'

end

app/views/layouts/_flash_message_center.html.erb
<% if flash[:success] %>
    <div class="success-message">
        <%= flash[:success] %>
    </div>
<% elsif flash[:error] %>
    <div class="error-message">
        <%= flash[:error] %>
    </div>
<% elsif flash[:errors] %>
    <div class="error-message">
        <p>Could not save your information for the following <%= "reason".pluralize(flash[:errors].count) %>:</p>
        <ul>
        <% flash[:errors].each do |error| %>
            <li><%= error %></li>
        <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tandem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,300;0,400;0,600;0,700;1,300;1,400&display=swap" rel="stylesheet">
  </head>

  <body>
    <div id="all-wrapper">
      <div id="header">
        <img id="logo" src="/images/logo.png" alt="Tandem Logo">
      </div>
      <div id="nav-wrap">
        <nav>
          <% if current_user %>
            <h3>LOGGED IN AS<br><strong><%= current_user.full_name.upcase %></strong></h3>
            
            <div><%= link_to "Home", home_path %>
            <div><%= link_to "My Tasks", mytasks_path %></div>
            <div class="line"> </div>
            <h4>PROJECTS</h4>
              <% current_user.projects.each do |project| %>
                <div>
                <%= link_to project.title, project_path(project) %>
                </div>
              <% end %>
              <div><em><small><%= link_to "All Projects List", projects_path %></small></em></div>
            <div class="line"> </div>
            <div><%= link_to "Settings", edit_user_path(current_user) %></div>
            <div><%= link_to "Logout", logout_path %></div>
          <% else %>
            <div><%= link_to "Log In", login_path %></div>
            <div><%= link_to "Sign up", new_user_path %></div>
          <% end %>

        </nav>
      </div>

      <div id="content-wrap">
        <%= yield %>
      </div>

      <div id="footer">
      </div>

    </div>
  </body>
</html>